packages:
  - apps/*
  - packages/*
allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@hono/node-server@2.1.3'
  - expo-constants@57.0.20
  - expo-modules-core@57.0.20
  - expo@57.0.26
  - hono@4.13.11
